// Generates migrations/seed.sql from the seed source data.
// Run: npm run seed:build   (uses tsx; Web Crypto is global in Node 18+)
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { hashPassword, uuid } from '../auth/crypto.ts';
import { ALL_SEED_VENDORS, type SeedVendor } from './data.ts';
import type { Role } from '../../shared/types.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));

const DEMO_PASSWORD = 'BridgeDemo2024!'; // handed to testers; >= 12 chars

function q(v: string | number | boolean | null | undefined): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/'/g, "''")}'`;
}

function iso(d: Date): string {
  return d.toISOString();
}

function daysAgo(n: number): Date {
  return new Date(Date.now() - n * 86400_000);
}

const lines: string[] = [];
lines.push('-- The Bridge seed data. Generated by worker/seed/build-seed.ts.');
lines.push('-- Demo login password for every seeded user: ' + DEMO_PASSWORD);
lines.push('PRAGMA foreign_keys=OFF;');

// --- Organisations ---
const gmcOrg = uuid();
const asOrg = uuid();
lines.push(
  `INSERT INTO organisations (id,name,type,created_at) VALUES ` +
    `(${q(gmcOrg)},${q('Global Media Content Ltd')},${q('gmc')},${q(iso(new Date()))}),` +
    `(${q(asOrg)},${q('AppSumo')},${q('client')},${q(iso(new Date()))});`,
);

// --- Users: one per role ---
interface SeedUser {
  role: Role;
  fullName: string;
  email: string;
  org: string;
}
const seedUsers: SeedUser[] = [
  { role: 'gmc_admin', fullName: 'Grace Adeyemi', email: 'admin@gmc.test', org: gmcOrg },
  { role: 'gmc_analyst', fullName: 'Marcus Feld', email: 'analyst@gmc.test', org: gmcOrg },
  { role: 'appsumo_exec', fullName: 'Priya Raman', email: 'exec@appsumo.test', org: asOrg },
  { role: 'appsumo_partnerships', fullName: 'Diego Santos', email: 'partnerships@appsumo.test', org: asOrg },
  { role: 'appsumo_support', fullName: 'Hana Kim', email: 'support@appsumo.test', org: asOrg },
  { role: 'appsumo_finance', fullName: 'Tom Reilly', email: 'finance@appsumo.test', org: asOrg },
];

const userIds: Record<Role, string> = {} as any;

async function main() {
  for (const u of seedUsers) {
    const id = uuid();
    userIds[u.role] = id;
    const { hash, salt } = await hashPassword(DEMO_PASSWORD);
    lines.push(
      `INSERT INTO users (id,email,full_name,role,organisation_id,password_hash,password_salt,failed_login_count,created_at) VALUES ` +
        `(${q(id)},${q(u.email)},${q(u.fullName)},${q(u.role)},${q(u.org)},${q(hash)},${q(salt)},0,${q(iso(new Date()))});`,
    );
  }

  const gmcAdmin = userIds['gmc_admin'];
  const gmcAnalyst = userIds['gmc_analyst'];

  const vendorIdBySlug = new Map<string, string>();

  // --- Vendors + score history + promises + issues + questions + themes ---
  const brokenPromiseTarget = 8;
  let brokenCount = 0;
  const promiseIdByVendorFirst = new Map<string, string>();

  for (const v of ALL_SEED_VENDORS) {
    const vid = uuid();
    const slug = v.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    vendorIdBySlug.set(slug, vid);

    // status changed recently for "changed this week" on a few vendors
    const statusChangedAt =
      v.status !== 'green' ? iso(daysAgo(3 + Math.floor(Math.random() * 3))) : null;
    const prevStatus =
      v.status === 'red' ? 'amber' : v.status === 'amber' ? 'green' : null;

    lines.push(
      `INSERT INTO vendors (id,name,slug,company_name,founder_name,deal_url,app_url,changelog_url,support_email,launch_date,tier_count,price_range,monitoring_group,health_score,status,previous_status,status_changed_at,last_vendor_update_at,last_vendor_reply_at,badge_level,consecutive_green_quarters,payout_held_pct,is_archived,is_demo_record,created_at,updated_at) VALUES (` +
        [
          q(vid),
          q(v.name),
          q(slug),
          q(v.company ?? null),
          q(v.founder ?? null),
          q(v.dealUrl ?? `https://appsumo.com/products/${slug}`),
          q(v.appUrl ?? `https://${slug}.example.com`),
          q(v.changelogUrl ?? `https://${slug}.example.com/changelog`),
          q(v.supportEmail ?? `support@${slug}.example.com`),
          q(v.launchDate ?? null),
          q(v.tierCount ?? null),
          q(v.priceRange ?? null),
          q(v.group),
          q(v.score),
          q(v.status),
          q(prevStatus),
          q(statusChangedAt),
          q(iso(daysAgo(v.status === 'red' ? 40 : 6))),
          q(iso(daysAgo(v.status === 'red' ? 50 : 9))),
          q(v.badge ?? 'none'),
          q(v.status === 'green' ? 2 : 0),
          q(v.status === 'red' ? 50 : 0),
          q(v.archived ?? false),
          q(v.demo ?? false),
          q(iso(daysAgo(120))),
          q(iso(new Date())),
        ].join(',') +
        `);`,
    );

    // Score history: weekly snapshots for the last 52 weeks, interpolating arc.
    buildScoreHistory(vid, v);

    // Promises
    v.promises.forEach((p, idx) => {
      const pid = uuid();
      if (idx === 0) promiseIdByVendorFirst.set(vid, pid);
      if (p.status === 'broken') brokenCount++;
      lines.push(
        `INSERT INTO promises (id,vendor_id,promise_text,source_type,source_url,promised_on,due_by,status,created_by,created_at,updated_at) VALUES (` +
          [
            q(pid),
            q(vid),
            q(p.text),
            q(p.source),
            q(`https://appsumo.com/products/${slug}#promise-${idx + 1}`),
            q(p.promisedOn ?? v.launchDate ?? null),
            q(p.dueBy ?? null),
            q(p.status),
            q(gmcAnalyst),
            q(iso(daysAgo(100 - idx))),
            q(iso(daysAgo(10))),
          ].join(',') +
          `);`,
      );
    });

    // Issues
    v.issues.forEach((is, idx) => {
      const iid = uuid();
      const detected = daysAgo(v.status === 'red' ? 30 - idx : 12 - idx);
      const severityHours = is.severity === 'serious' ? 24 : 72;
      const due = new Date(detected.getTime() + severityHours * 3600_000);
      const team = is.team ?? 'gmc';
      lines.push(
        `INSERT INTO issues (id,vendor_id,title,description,failure_mode,severity,board_stage,assigned_team,assigned_user_id,due_at,sla_state,detected_at,resolved_at,resolution_note,created_by,created_at,updated_at) VALUES (` +
          [
            q(iid),
            q(vid),
            q(is.title),
            q(is.description ?? null),
            q(is.failureMode),
            q(is.severity),
            q(is.stage),
            q(team),
            q(team === 'gmc' ? gmcAnalyst : userIds['appsumo_partnerships']),
            q(iso(due)),
            q('on_track'),
            q(iso(detected)),
            q(is.stage === 'resolved' ? iso(daysAgo(2)) : null),
            q(is.resolutionNote ?? null),
            q(gmcAnalyst),
            q(iso(detected)),
            q(iso(new Date())),
          ].join(',') +
          `);`,
      );
    });

    // Unanswered questions
    (v.questions ?? []).forEach((qn) => {
      lines.push(
        `INSERT INTO unanswered_questions (id,vendor_id,question_text,source_url,asked_on,days_unanswered) VALUES (` +
          [
            q(uuid()),
            q(vid),
            q(qn.text),
            q(`https://appsumo.com/products/${slug}#q`),
            q(qn.askedOn),
            q(qn.days),
          ].join(',') +
          `);`,
      );
    });

    // Complaint themes for the last 8 weeks (amber/red vendors)
    if ((v.status !== 'green' || v.sliding) && (v.complaintThemes?.length ?? 0) > 0) {
      for (let w = 0; w < 8; w++) {
        const weekStart = iso(daysAgo((w + 1) * 7)).slice(0, 10);
        v.complaintThemes!.forEach((ct) => {
          const count = Math.max(1, Math.round((8 - w) * (v.status === 'red' ? 3 : 1.5)));
          lines.push(
            `INSERT INTO complaint_themes (id,vendor_id,week_starting,theme,mention_count,sample_quote,is_matched_to_promise,created_at) VALUES (` +
              [
                q(uuid()),
                q(vid),
                q(weekStart),
                q(ct.theme),
                q(count),
                q(ct.sample),
                q(false),
                q(iso(daysAgo((w + 1) * 7))),
              ].join(',') +
              `);`,
          );
        });
      }
    }
  }

  // --- Extra issues to reach 18 total and cover every stage + failure mode ---
  const extraIssues: {
    slug: string;
    title: string;
    fm: string;
    sev: 'minor' | 'notable' | 'serious';
    stage: string;
    team: string;
  }[] = [
    { slug: 'northwind-analytics', title: 'Dashboard exports intermittently failing', fm: 'support_failure', sev: 'minor', stage: 'spotted', team: 'support' },
    { slug: 'kestrel-forms', title: 'Founder hints at pivot to enterprise-only', fm: 'pivot', sev: 'notable', stage: 'spotted', team: 'gmc' },
    { slug: 'larkspur-crm', title: 'Product updates have gone quiet for 3 months', fm: 'slow_death', sev: 'notable', stage: 'vendor_contacted', team: 'partnerships' },
    { slug: 'tindal-mail', title: 'Support tickets unanswered beyond SLA', fm: 'support_failure', sev: 'notable', stage: 'confirmed', team: 'support' },
    { slug: 'ashfield-helpdesk', title: 'App unreachable for a full day, no status page', fm: 'vanishing', sev: 'serious', stage: 'vendor_contacted', team: 'gmc' },
  ];
  for (const e of extraIssues) {
    const vid = vendorIdBySlug.get(e.slug);
    if (!vid) continue;
    const detected = daysAgo(8);
    const due = new Date(detected.getTime() + (e.sev === 'serious' ? 24 : 72) * 3600_000);
    lines.push(
      `INSERT INTO issues (id,vendor_id,title,failure_mode,severity,board_stage,assigned_team,assigned_user_id,due_at,sla_state,detected_at,created_by,created_at,updated_at) VALUES (` +
        [
          q(uuid()), q(vid), q(e.title), q(e.fm), q(e.sev), q(e.stage), q(e.team),
          q(e.team === 'gmc' ? gmcAnalyst : userIds['appsumo_partnerships']),
          q(iso(due)), q('on_track'), q(iso(detected)), q(gmcAnalyst), q(iso(detected)), q(iso(new Date())),
        ].join(',') +
        `);`,
    );
  }

  // --- Approvals: 3 pending ---
  const yapperId = vendorIdBySlug.get('yapper')!;
  const adiloId = vendorIdBySlug.get('adilo')!;
  const cosmosId = vendorIdBySlug.get('cosmos-video')!;
  const approvals = [
    {
      type: 'payout_hold',
      vendor: yapperId,
      title: 'Hold 50% of Yapper payout pending resolution',
      rec: 'Withhold half of the next payout until refills are restored or refunds issued.',
      rationale: 'Four of five core promises are broken; buyers materially harmed.',
    },
    {
      type: 'formal_notice',
      vendor: adiloId,
      title: 'Issue formal notice to Adilo',
      rec: 'Send a formal notice requiring cancelled lifetime plans to be reinstated.',
      rationale: 'Vendor continued cancelling paid lifetime plans after buyer advocacy.',
    },
    {
      type: 'buyer_protection',
      vendor: cosmosId,
      title: 'Extend buyer protection to Cosmos Video purchasers',
      rec: 'Offer AppSumo credit to affected Cosmos Video lifetime buyers.',
      rationale: 'Lifetime plans cancelled; only a coupon offered as remedy.',
    },
  ];
  for (const a of approvals) {
    const due = new Date(Date.now() + 5 * 86400_000);
    lines.push(
      `INSERT INTO approvals (id,type,vendor_id,title,recommendation,rationale,status,requested_by,due_at,created_at) VALUES (` +
        [
          q(uuid()),
          q(a.type),
          q(a.vendor),
          q(a.title),
          q(a.rec),
          q(a.rationale),
          q('pending'),
          q(gmcAdmin),
          q(iso(due)),
          q(iso(daysAgo(1))),
        ].join(',') +
        `);`,
    );
  }

  // --- Honours lists: one approved last month, one draft this month ---
  const thisMonth = new Date();
  const firstThis = new Date(Date.UTC(thisMonth.getUTCFullYear(), thisMonth.getUTCMonth(), 1));
  const firstLast = new Date(Date.UTC(thisMonth.getUTCFullYear(), thisMonth.getUTCMonth() - 1, 1));

  const greenSlugsForHonours = ['qolaba', 'northwind-analytics', 'kestrel-forms', 'larkspur-crm', 'vellum-docs'];
  const greenIds = greenSlugsForHonours
    .map((s) => vendorIdBySlug.get(s))
    .filter((x): x is string => Boolean(x));

  const draftList = uuid();
  lines.push(
    `INSERT INTO honours_lists (id,month,title,status,created_at) VALUES (` +
      [q(draftList), q(iso(firstThis).slice(0, 10)), q(`Honours — ${iso(firstThis).slice(0, 7)}`), q('draft'), q(iso(daysAgo(2)))].join(',') +
      `);`,
  );
  const approvedList = uuid();
  lines.push(
    `INSERT INTO honours_lists (id,month,title,status,submitted_at,approved_by,approved_at,published_at,created_at) VALUES (` +
      [
        q(approvedList),
        q(iso(firstLast).slice(0, 10)),
        q(`Honours — ${iso(firstLast).slice(0, 7)}`),
        q('approved'),
        q(iso(daysAgo(35))),
        q(userIds['appsumo_exec']),
        q(iso(daysAgo(31))),
        q(iso(daysAgo(30))),
        q(iso(daysAgo(36))),
      ].join(',') +
      `);`,
  );
  const citations = [
    'Confirmed no limit change for lifetime buyers in writing.',
    'Shipped every roadmap item promised at launch.',
    'Fastest support response in the portfolio this quarter.',
    'Grew features without touching LTD entitlements.',
    'Transparent changelog and proactive buyer comms.',
  ];
  greenIds.forEach((vid, i) => {
    lines.push(
      `INSERT INTO honours_entries (id,honours_list_id,vendor_id,position,citation,is_swapped_out,created_at) VALUES (` +
        [q(uuid()), q(draftList), q(vid), q(i + 1), q(citations[i % citations.length]), q(false), q(iso(daysAgo(2)))].join(',') +
        `);`,
    );
    lines.push(
      `INSERT INTO honours_entries (id,honours_list_id,vendor_id,position,citation,is_swapped_out,created_at) VALUES (` +
        [q(uuid()), q(approvedList), q(vid), q(i + 1), q(citations[(i + 1) % citations.length]), q(false), q(iso(daysAgo(35)))].join(',') +
        `);`,
    );
  });

  // --- Reports: one of each type ---
  const reports = [
    { type: 'monday', title: 'Monday heads-up — portfolio status', body: mondayReport() },
    { type: 'monthly', title: 'Monthly report — portfolio health', body: '# Monthly report\n\nGreen holding steady. Two vendors on the sliding watch. Yapper and Adilo escalated.\n' },
    { type: 'quarterly', title: 'Quarterly review — promises kept vs broken', body: '# Quarterly review\n\nAcross the portfolio, promise-keeping improved except for four documented failures.\n' },
    { type: 'evidence_pack', title: 'Evidence pack — Yapper', body: '# Evidence pack: Yapper\n\nDocumented conversion of monthly refills to one-time credits. See promise register.\n', vendor: yapperId },
  ];
  for (const r of reports) {
    lines.push(
      `INSERT INTO reports (id,type,title,period_start,period_end,body_markdown,vendor_id,published_at,created_by,created_at) VALUES (` +
        [
          q(uuid()),
          q(r.type),
          q(r.title),
          q(iso(daysAgo(30)).slice(0, 10)),
          q(iso(new Date()).slice(0, 10)),
          q(r.body),
          q((r as any).vendor ?? null),
          q(iso(daysAgo(1))),
          q(gmcAnalyst),
          q(iso(daysAgo(2))),
        ].join(',') +
        `);`,
    );
  }

  // --- A couple of seed notifications for the exec ---
  lines.push(
    `INSERT INTO notifications (id,user_id,type,title,body,parent_type,is_read,created_at) VALUES (` +
      [q(uuid()), q(userIds['appsumo_exec']), q('approval_requested'), q('3 approvals awaiting your decision'), q('Payout hold, formal notice, buyer protection'), q('approval'), q(false), q(iso(daysAgo(1)))].join(',') +
      `);`,
  );

  lines.push('PRAGMA foreign_keys=ON;');
  lines.push(`-- broken promises seeded: ${brokenCount} (target >= ${brokenPromiseTarget})`);

  const out = resolve(__dirname, '../../seed.sql');
  writeFileSync(out, lines.join('\n') + '\n');
  console.log(`Wrote ${out}`);
  console.log(`Vendors: ${ALL_SEED_VENDORS.length}, broken promises: ${brokenCount}`);
}

function buildScoreHistory(vid: string, v: SeedVendor) {
  // Interpolate the 12-point arc into 52 weekly points (oldest -> newest).
  const arc = v.scoreArc;
  const weeks = 52;
  for (let w = 0; w < weeks; w++) {
    const t = (w / (weeks - 1)) * (arc.length - 1);
    const i0 = Math.floor(t);
    const i1 = Math.min(arc.length - 1, i0 + 1);
    const frac = t - i0;
    let score = Math.round(arc[i0] + (arc[i1] - arc[i0]) * frac);
    const recordedAt = daysAgo((weeks - 1 - w) * 7);

    // Sliding vendors: still green, but down 18 points over the last ~35 days.
    // The high point sits at ~35 days ago (w = weeks-6) so it falls just OUTSIDE
    // the 30-day window the early-warning panel compares against.
    const slideStart = weeks - 6; // ~35 days ago
    if (v.sliding && w >= slideStart) {
      const from = v.score + 18;
      const span = weeks - 1 - slideStart;
      const step = (v.score - from) / span;
      score = Math.round(from + step * (w - slideStart));
    }
    const status =
      score >= 70 ? 'green' : score >= 45 ? 'amber' : 'red';
    lines.push(
      `INSERT INTO score_history (id,vendor_id,recorded_at,health_score,status,promise_component,momentum_component,liveness_component,support_component,sentiment_component) VALUES (` +
        [
          q(uuid()),
          q(vid),
          q(iso(recordedAt)),
          q(Math.max(2, Math.min(98, score))),
          q(v.sliding && w >= slideStart ? 'green' : status),
          q(Math.round(score * 0.9)),
          q(Math.round(score * 1.05)),
          q(Math.round(score * 0.95)),
          q(Math.round(score * 1.0)),
          q(Math.round(score * 0.85)),
        ].join(',') +
        `);`,
    );
  }
}

function mondayReport(): string {
  return [
    '# Monday heads-up',
    '',
    'Three items likely to generate tickets this week:',
    '',
    '- **Yapper** — refills converted to one-time credits. Say: escalated, formal notice issued.',
    '- **JoggAI** — BYOK now required for top models. Say: under review with the vendor.',
    '- **Cosmos Video** — plans cancelled, coupon offered. Say: buyer protection being considered.',
    '',
    'Two green vendors are on the sliding watch. No action needed yet.',
  ].join('\n');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
